[env]
term = "alacritty"

[general]
live_config_reload = true

[window]
opacity = 1.0

[font]
size = 13.0

[font.normal]
family = "Monofur Nerd Font Mono"

[colors.primary]
background = "#32383b"
foreground = "#f9e2af"

[colors.normal]
black   = "#32383b"
red     = "#f38ba8"
green   = "#70abaf"
yellow = "#00ff00"
blue    = "#ff6542"
magenta = "#ff0000"
cyan  = "#fcbf3b"
white   = "#0000ff"

[colors.bright]
black   = "#32383b"
red     = "#f38ba8"
green   = "#70abaf"
yellow = "#00ff00"
blue    = "#ff6542"
magenta = "#ff0000"
cyan  = "#fcbf3b"
white   = "#0000ff"

[colors.selection]
text       = "#000000"
background = "#E8B4B8"

[colors.search.matches]
foreground = "#FDFCF9"
background = "#D85A5A"

[colors.search.focused_match]
foreground = "#000000"
background = "#FF8A95"

[colors.cursor]
text   = "#000000"
cursor = "#FF8A95"    # bright sakura pink â€“ impossible to miss

[colors.line_indicator]
background = "#FFE6E8"   # subtle sakura-tinted current line

[cursor.style]
shape = "Block"
blinking = "Off"
